/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Miguel Flores
 */
public class Gnode extends javax.swing.JPanel {

    protected char nombre;
    protected ArrayList<Arista> destinos = new ArrayList();
    public int dest = 0;
    public int x11;
    public int y11;

    public Arista a_pop() {
        if (destinos.size() > 0) {
            Arista u = destinos.get(0);
            destinos.remove(0);
            return u;
        } else {
            return null;
        }
    }

    public Gnode(JPanel contenedor, int x1, int y1, char node) {
        this.x11=x1;
        this.y11=y1;
        initComponents();
        Component add = contenedor.add(this);
        this.setBounds(x1, y1, 59, 57);
        this.nombre = node;
        lbl_node.setText(node + "");
        int dest1 = this.dest;
        
    }

    public char getNombre() {
        return nombre;
    }

    public void setNombre(char nombre) {
        this.nombre = nombre;
    }

    public ArrayList<Arista> getDestinos() {
        return destinos;
    }

    public void setDestinos(Arista destinos) {
        this.destinos.add(destinos);
        dest++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_node = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_node.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_node.setForeground(new java.awt.Color(255, 255, 255));
        lbl_node.setText(" ");
        lbl_node.setPreferredSize(new java.awt.Dimension(16, 22));
        add(lbl_node, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 17, 27, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clases/Untitled.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mover = true;
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        mover = false;
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x1 = this.getX(), y1 = this.getY();
        if (mover) {
            x1 += evt.getX() - x;
            y1 += evt.getY() - y;
            this.setLocation(x1, y1);
            lastx = this.getX();
            lasty = this.getY();
        }
    }//GEN-LAST:event_formMouseDragged

    boolean mover;
    int x, y;
    private int lasty = 50;
    private int lastx = 50;

    public int getLasty() {
        return lasty;
    }

    public void setLasty(int lasty) {
        this.lasty = lasty;
    }

    public int getLastx() {
        return lastx;
    }

    public void setLastx(int lastx) {
        this.lastx = lastx;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_node;
    // End of variables declaration//GEN-END:variables

    @Override
    public String toString() {
        return nombre + "";
    }

}
